/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Pegawai;
import Model.Toko;
import Model.Wahana;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;



/**
 *
 * @author naufal mukhbit
 */
public class AMP extends javax.swing.JFrame {

    /**
     * Creates new form AMP
     */
    public AMP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pWahana = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWahana = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        isiWahana = new javax.swing.JTextArea();
        btnAddWhn = new javax.swing.JButton();
        btnDeleteWhn = new javax.swing.JButton();
        btnEditWhn = new javax.swing.JButton();
        pPegawai = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        isiPegawai = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPegawai = new javax.swing.JList<>();
        btnDeletePgw = new javax.swing.JButton();
        btnAddPgw = new javax.swing.JButton();
        btnEditPgw = new javax.swing.JButton();
        pToko = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        listToko = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        isiToko = new javax.swing.JTextArea();
        btnDeleteToko = new javax.swing.JButton();
        btnEditToko = new javax.swing.JButton();
        btnAddToko = new javax.swing.JButton();

        jScrollPane5.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listWahana);

        isiWahana.setEditable(false);
        isiWahana.setColumns(20);
        isiWahana.setRows(5);
        jScrollPane2.setViewportView(isiWahana);

        btnAddWhn.setText("Tambah");

        btnDeleteWhn.setText("Hapus");

        btnEditWhn.setText("Ubah");

        javax.swing.GroupLayout pWahanaLayout = new javax.swing.GroupLayout(pWahana);
        pWahana.setLayout(pWahanaLayout);
        pWahanaLayout.setHorizontalGroup(
            pWahanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWahanaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pWahanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pWahanaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pWahanaLayout.createSequentialGroup()
                        .addComponent(btnAddWhn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditWhn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteWhn)))
                .addContainerGap())
        );
        pWahanaLayout.setVerticalGroup(
            pWahanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pWahanaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pWahanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pWahanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteWhn)
                    .addComponent(btnAddWhn)
                    .addComponent(btnEditWhn))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Wahana", pWahana);

        isiPegawai.setColumns(20);
        isiPegawai.setRows(5);
        jScrollPane3.setViewportView(isiPegawai);

        jScrollPane4.setViewportView(listPegawai);

        btnDeletePgw.setText("Hapus");

        btnAddPgw.setText("Tambah");

        btnEditPgw.setText("Ubah");

        javax.swing.GroupLayout pPegawaiLayout = new javax.swing.GroupLayout(pPegawai);
        pPegawai.setLayout(pPegawaiLayout);
        pPegawaiLayout.setHorizontalGroup(
            pPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPegawaiLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPegawaiLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddPgw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditPgw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletePgw)))
                .addContainerGap())
        );
        pPegawaiLayout.setVerticalGroup(
            pPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletePgw)
                    .addComponent(btnAddPgw)
                    .addComponent(btnEditPgw))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Pegawai", pPegawai);

        jScrollPane6.setViewportView(listToko);

        isiToko.setColumns(20);
        isiToko.setRows(5);
        jScrollPane7.setViewportView(isiToko);

        btnDeleteToko.setText("Hapus");

        btnEditToko.setText("Ubah");

        btnAddToko.setText("Tambah");

        javax.swing.GroupLayout pTokoLayout = new javax.swing.GroupLayout(pToko);
        pToko.setLayout(pTokoLayout);
        pTokoLayout.setHorizontalGroup(
            pTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTokoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTokoLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTokoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddToko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditToko)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteToko)))
                .addContainerGap())
        );
        pTokoLayout.setVerticalGroup(
            pTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTokoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteToko)
                    .addComponent(btnEditToko)
                    .addComponent(btnAddToko))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Toko", pToko);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AMP().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPgw;
    private javax.swing.JButton btnAddToko;
    private javax.swing.JButton btnAddWhn;
    private javax.swing.JButton btnDeletePgw;
    private javax.swing.JButton btnDeleteToko;
    private javax.swing.JButton btnDeleteWhn;
    private javax.swing.JButton btnEditPgw;
    private javax.swing.JButton btnEditToko;
    private javax.swing.JButton btnEditWhn;
    private javax.swing.JTextArea isiPegawai;
    private javax.swing.JTextArea isiToko;
    private javax.swing.JTextArea isiWahana;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JList<String> listPegawai;
    private javax.swing.JList<String> listToko;
    private javax.swing.JList<String> listWahana;
    private javax.swing.JPanel pPegawai;
    private javax.swing.JPanel pToko;
    private javax.swing.JPanel pWahana;
    // End of variables declaration//GEN-END:variables
    public JButton getBtnAddPgw() {
        return btnAddPgw;
    }

    public JButton getBtnAddToko() {
        return btnAddToko;
    }

    public JButton getBtnAddWhn() {
        return btnAddWhn;
    }

    public JButton getBtnDeletePgw() {
        return btnDeletePgw;
    }

    public JButton getBtnDeleteToko() {
        return btnDeleteToko;
    }

    public JButton getBtnDeleteWhn() {
        return btnDeleteWhn;
    }

    public JButton getBtnEditPgw() {
        return btnEditPgw;
    }

    public JButton getBtnEditToko() {
        return btnEditToko;
    }

    public JButton getBtnEditWhn() {
        return btnEditWhn;
    }

    public void reset() {
        isiWahana.setText("");
        isiPegawai.setText("");
        isiToko.setText("");
    }

    public void setListPegawai(List<Pegawai> lp) {
        DefaultListModel listModel = new DefaultListModel();
        for(Pegawai p:lp) {
            listModel.addElement(p);
        }
        listPegawai = new JList(listModel);
    }

    public void setListToko(List<Toko> lt) {
        DefaultListModel listModel = new DefaultListModel();
        for(Toko t:lt) {
            listModel.addElement(t);
        }
        listToko = new JList(listModel);
    }

    public void setListWahana(List<Wahana> lw) {
        DefaultListModel listModel = new DefaultListModel();
        for(Wahana w:lw) {
            listModel.addElement(w);
        }
        listWahana = new JList(listModel);
    }

    public void setIsiPegawai(String s) {
        isiPegawai.setText(s);
    }

    public void setIsiToko(String s) {
        isiToko.setText(s);
    }

    public void setIsiWahana(String s) {
        isiWahana.setText(s);
    }
    
    public void addActionListener(ActionListener e) {
        this.btnAddWhn.addActionListener(e);
        
    }
}
